### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by TechnologyClassroom** [apertium/apertium-simpleton#3]
I am having difficulty building this on Trisquel 8 (based on Ubuntu 16.04) and I do not see any build instructions in this repo or the wiki http://wiki.apertium.org/wiki/Apertium_Simpleton_UI

I already had several qt5 dependencies.

    git clone https://github.com/apertium/apertium-simpleton
    cd apertium-simpleton
    qmake -project
    qmake
    make

I have added some parts to the `Makefile` such as ` -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork` to the `INCPATH`.  Now I get:

    src/installer.cpp:21:26: fatal error: ui_installer.h: No such file or directory

Do you have a build script or a set of commands that worked for you?  If we get a working set, I would be happy to make a `README.md` for this project.

**Comment by TinoDidriksen** [comment]
Don't run `qmake -project` - that overwrites the existing `apertium-simpleton.pro` with an auto-generated file that doesn't work.

**Comment by TinoDidriksen** [comment]
However, why are you building from source on Ubuntu 16.04? Use the package from the nightly apt-get repo.

**Comment by TechnologyClassroom** [comment]
That worked!  I was able to build by undoing the change I made with `qmake -project` using `git checkout apertium-simpleton.pro`.

Install failed, but the program is compiled in the directory.

```
$ sudo make install
make: Nothing to be done for 'install'.
```

I can run it with `./apertium-simpleton`
