### ISSUE TITLE
Manually Install Packages

### ISSUE THREAD

**Issue by tooolbox** [apertium/apertium-simpleton#5]
I downloaded this for use on a Windows machine that is not internet-connected.

Is there a way for me to install the core tools and/or language packs by downloading them and sticking them in folders, or something similar?

**Comment by TinoDidriksen** [comment]
You can install a bunch of packages you want, then copy the resulting `%APPDATA%\Tino Didriksen Consult\` folder (I should change that name).

**Comment by tooolbox** [comment]
Thanks.

To complicate matters, I'm dealing with a corporate proxy (your app has no proxy awareness AFAICT) so I need to download and unpack whatever packages via browser and manually construct folders.  Would this be possible?

I do see the `Tino Didriksen Consult` folder and the `.ini` file but I am not sure what to put in there.  A typical sample should be enough to get me rolling, if you have something like that.

**Comment by TinoDidriksen** [comment]
What I meant was to perform the install on a computer with net access, then copy the result to the offline computer.

Manually installing also requires changing the .ini file to tell what's installed.

As for proxy support, that's also a good idea. But this app is kinda superfluous these days, thanks to being able to run the full Ubuntu version in [Windows 10's WSL](https://docs.microsoft.com/windows/wsl).

**Comment by tooolbox** [comment]
> What I meant was to perform the install on a computer with net access, then copy the result to the offline computer.

Yeah, understood.  I'll take a stab at that.

> As for proxy support, that's also a good idea. But this app is kinda superfluous these days, thanks to being able to run the full Ubuntu version in Windows 10's WSL.

...Well, unless you want to run it on an older machine, which is the case for me.
